author_id = "demo"
app_id = "go-scores"
author_name = "Demo"
app_name = "Scores Demo (Go)"

[files]
font = { path = "eg_6x10.fff", url = "https://fonts.fireflyzero.com/fonts/ascii/eg_6x10.fff" }

[boards]
1 = { name = "default" }
